### ISSUE TITLE
Do not wait endlessly whether a collection is in sync.

### ISSUE THREAD

**Issue by hkernbach** [arangodb/rta-makedata#1]
Do not wait endlessly whether a collection is in sync.
We should define a maximum amount for re-tries. 

See code location:
https://github.com/arangodb/rta-makedata/blob/cadff1b1298d9c80d9dc85e42ae4b849d9dcb3a8/test_data/tests/js/server/cluster/wait_for_shards_in_sync.js#L17-L35

**Comment by dothebart** [comment]
hm, at the moment we do this by deadline in RTA. We should do that https://github.com/arangodb/arangodb/blob/devel/js/client/modules/%40arangodb/testsuites/rta_makedata.js#L127 here as well.

**Comment by dothebart** [comment]
https://github.com/arangodb/rta-makedata/pull/9 marking as resolved.
